### ISSUE TITLE
other agents ?

### ISSUE THREAD

**Issue by zhangh-dev** [Liang-ZX/VectorNet#1]
Have you consider the other agents ? There seems to be no in the implementation.

**Comment by Liang-ZX** [comment]
Yes, this implementation does not include multi-agents, because the question of the summer camp is  a little different from the original paper.

**Comment by Liang-ZX** [comment]
> Have you consider the other agents ? There seems to be no in the implementation.

Yes, this implementation does not include multi-agents, because the question of the summer camp is a little different from the original paper.
