### ISSUE TITLE
代码用的数据集是argoverse1还是1.1还是2啊

### ISSUE THREAD

**Issue by chg0901** [Liang-ZX/VectorNet#5]
argoverse数据集有几个不同版本，请问代码之前运行测试的时候，使用什么版本，

**Comment by Liang-ZX** [comment]
> argoverse数据集有几个不同版本，请问代码之前运行测试的时候，使用什么版本，

1.1

**Comment by chg0901** [comment]
> > argoverse数据集有几个不同版本，请问代码之前运行测试的时候，使用什么版本，
> 
> 1.1

谢谢回复，多谢啦
